In [1]:
import numpy as np
import pandas as pd

In [2]:
route = pd.read_csv(r"C:\Users\Priya\Downloads\DATA SETS\correct.csv")

In [5]:
route.head()

,time_step,distance_remaining,speed,weather_condition,road_traffic_density,vehicle_condition,festival,time_taken,delay_remaining
0,0,499.859,50.60,sunny,high,good,no,-2,4.31
1,10,499.679,64.85,sunny,moderate,good,no,8,2.65
2,20,499.536,51.42,sunny,low,poor,no,18,7.44
3,30,499.460,27.36,cloudy,jam,good,no,31,1.06
4,40,499.267,69.48,clear,low,good,yes,42,4.90

In [4]:
route.tail()

,time_step,distance_remaining,speed,weather_condition,road_traffic_density,vehicle_condition,festival,time_taken,delay_remaining
99995,999950,0.0,0.0,clear,low,good,no,999950,0.0
99996,999960,0.0,0.0,clear,low,good,no,999959,0.0
99997,999970,0.0,0.0,clear,low,good,no,999969,0.0
99998,999980,0.0,0.0,clear,low,good,no,999981,0.0
99999,999990,0.0,0.0,clear,low,good,no,999989,0.0